---
apiVersion: v1
kind: Service
metadata:
  namespace: ms-demo
  name: vf-meetingapi
  labels:
    app: vf-meetingapi
    solution: vf-meeting-action
spec:
  type: ClusterIP
  ports:
    - port: 8090
      targetPort: 8090
  selector:
    app: vf-meetingapi

 
---
apiVersion: v1
data:
  mongo.address: vf-mongo:27017
kind: ConfigMap
metadata:
  name: mongo-config2
  namespace: ms-demo


---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ms-demo
  name: vf-meetingapi
  labels:
    app: vf-meetingapi
    solution: vf-meeting-action  
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: vf-meetingapi  
  template:
    metadata:
      labels:
        app: vf-meetingapi
    spec:
      containers:
        - name: vf-meetingapi
          image: ms-demo/meetingapi:0.1.0
          env:
            # Define the environment variable
            - name: SPECIAL_LEVEL_KEY
              valueFrom:
                configMapKeyRef:
                  # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                  name: mongo-config
                  # Specify the key associated with the value
                  key: mongo.address
          ports:
            - containerPort: 8090
      imagePullSecrets:
      - name: ms-demo-secret
      