---
apiVersion: v1
kind: Service
metadata:
  namespace: ms-demo
  name: vf-meetingui
  labels:
    app: vf-meetingui
    solution: vf-meeting-action
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: vf-meetingui


---
apiVersion: v1
kind: Service
metadata:
  namespace: ms-demo
  name: vf-meetingui-nodeport
  labels:
    app: vf-meetingui
    solution: vf-meeting-action
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
  selector:
    app: vf-meetingui     

 
---
apiVersion: v1
data:
  meetingapi.host: vf-meetingapi
  meetingapi.port: "8090"
kind: ConfigMap
metadata:
  name: meetingapi-config
  namespace: ms-demo


---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ms-demo
  name: vf-meetingui
  labels:
    app: vf-meetingui
    solution: vf-meeting-action  
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: vf-meetingui  
  template:
    metadata:
      labels:
        app: vf-meetingui
    spec:
      containers:
        - name: vf-meetingui
          image: mycluster.icp:8500/ms-demo/meetingui:0.1.0
          env:
            # Define the environment variable
            - name: MEETING_API_HOST
              valueFrom:
                configMapKeyRef:
                  # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                  name: meetingapi-config
                  # Specify the key associated with the value
                  key: meetingapi.host
            - name: MEETING_API_PORT
              valueFrom:
                configMapKeyRef:
                  # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                  name: meetingapi-config
                  # Specify the key associated with the value
                  key: meetingapi.port
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ms-demo-secret
      