---
apiVersion: v1
kind: Service
metadata:
  name: vf-meetingUi
  labels:
    app: vf-meetingUi
    solution: vf-meeting-action
  spec:
    type: CLusterIP
    ports:
    - port: 8090
      targetPort: 8090
    selector:
      app: vf-meetingUi

 ---
apiVersion: app/v1
kind: Deployment
metadata:
  ame: vf-meetingUi
  abels:
    app: vf-meetingUi
    solution: vf-meeting-action  
  spec:
    replica: 1
    selector: 
      matchLabel:
        app: vf-meetingUi  
    template:
      metadata:
        labels:
          app: vf-meetingUi
      spec:
        containers:
          - name: vf-meetingUi
            image: vfdemo/meetingUi:0.1.0
          ports:
            - containerPort: 8090        
     