---
apiVersion: v1
kind: Service
metadata:
  namespace: ms-demo
  name: vf-meetingApi
  labels:
    app: vf-meetingApi
    solution: vf-meeting-action
  spec:
    type: CLusterIP
    ports:
    - port: 8090
      targetPort: 8090
    selector:
      app: vf-meetingApi

 
---
apiVersion: v1
data:
  mongo.host: vf-mongo
  mongo.ip: 27017
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: ms-demo


---
apiVersion: app/v1
kind: Deployment
metadata:
  namespace: ms-demo
  name: vf-meetingApi
  labels:
    app: vf-meetingApi
    solution: vf-meeting-action  
  spec:
    replica: 1
    selector: 
      matchLabel:
        app: vf-meetingApi  
    template:
      metadata:
        labels:
          app: vf-meetingApi
      spec:
        containers:
          - name: vf-meetingApi
            image: vfdemo/meetingapi:0.1.0
            env:
              # Define the environment variable
              - name: SPECIAL_LEVEL_KEY
               valueFrom:
                 configMapKeyRef:
                   # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                   name: mongo-config
                   # Specify the key associated with the value
                   key: mongo.host
                   key: mongo.ip
          ports:
            - containerPort: 8090        
     